### ISSUE TITLE
Missing find in the JVM?

### ISSUE THREAD

**Issue by michbarsinai** [codeworth-gh/HearUsPlatform#128]
This initiated a coordinated shutdown. Maybe switch to GraalVM?/JDK11?

```
2020-06-22 09:12:54,740 [ERROR] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-29218 - Uncaught error from thread [app
lication-akka.actor.default-dispatcher-29224]: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/r
esources.jar, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.InternalError: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/resources.jar
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1052)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:302)
        at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1264)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1093)
        at java.lang.ClassLoader.getResource(ClassLoader.java:1091)
        at java.lang.ClassLoader.getSystemResource(ClassLoader.java:1226)
        at java.lang.ClassLoader.getSystemResourceAsStream(ClassLoader.java:1329)
        at java.lang.Class.getResourceAsStream(Class.java:2221)
        at java.net.IDN.<clinit>(IDN.java:237)
        at org.apache.commons.mail.util.IDNEmailAddressConverter.toASCII(IDNEmailAddressConverter.java:50)
        at org.apache.commons.mail.Email.createInternetAddress(Email.java:1949)
        at org.apache.commons.mail.Email.setFrom(Email.java:757)
        at org.apache.commons.mail.Email.setFrom(Email.java:740)
        at play.api.libs.mailer.CommonsMailer.$anonfun$createEmail$2(CommonsMailer.scala:32)
        at play.api.libs.mailer.CommonsMailer.$anonfun$createEmail$2$adapted(CommonsMailer.scala:32)
        at play.api.libs.mailer.CommonsMailer.setAddress(CommonsMailer.scala:119)
        at play.api.libs.mailer.CommonsMailer.createEmail(CommonsMailer.scala:32)
        at play.api.libs.mailer.CommonsMailer.send(CommonsMailer.scala:27)
        at play.api.libs.mailer.SMTPMailer.send(SMTPMailer.scala:24)
        at play.api.libs.mailer.SMTPDynamicMailer.send(SMTPDynamicMailer.scala:8)
        at actors.EmailSendingActor$$anonfun$receive$1.$anonfun$applyOrElse$5(EmailSendingActor.scala:56)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.io.FileNotFoundException: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre/lib/resources.jar
        at sun.misc.URLClassPath$JarLoader.getJarFile(URLClassPath.java:938)
        at sun.misc.URLClassPath$JarLoader.access$800(URLClassPath.java:801)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:886)
        at sun.misc.URLClassPath$JarLoader$1.run(URLClassPath.java:879)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath$JarLoader.ensureOpen(URLClassPath.java:878)
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1050)
        ... 33 common frames omitted
```

**Comment by michbarsinai** [comment]
Seem to have been cause by a JVM upgrade:

https://bugzilla.redhat.com/show_bug.cgi?id=1206856
